In [63]:
import pandas as pd

# Load data

In [64]:
df1 = pd.read_csv('data/prepared01.csv')
df2 = pd.read_csv('data/prepared02.csv')

df3_1 = pd.read_csv('data/prepared03-1.csv')
df3_2 = pd.read_csv('data/prepared03-2.csv')
df3_3 = pd.read_csv('data/prepared03-3.csv')
df3_4 = pd.read_csv('data/prepared03-4.csv')

df4 = pd.read_csv('data/prepared04.csv')
df5 = pd.read_csv('data/prepared05.csv')

### Combine data

In [65]:
df = pd.concat([df1, df2, df3_1, df3_2, df3_3, df3_4, df4, df5], ignore_index=True)
len(df)

1587777

In [66]:
df1.head()

,Unnamed: 0,time,language,source,group,hashtag
0,0,2019-09-27 17:15:51,en,Twitter for iPhone,17 pm,['KCON2019THAILAND']
1,1,2019-09-27 17:15:51,th,Twitter for Android,17 pm,"['BamBam', 'GOT7', 'Got7Homecoming', 'WelcomeG..."
2,2,2019-09-27 17:15:51,es,Twitter for iPhone,17 pm,"['X1', 'X1FlyHighToThailand', 'KCON19TH']"
3,3,2019-09-27 17:15:51,en,Twitter for Android,17 pm,"['KIMWOOSEOK', 'WelcomeX1toThailand']"
4,4,2019-09-27 17:15:51,th,Twitter for Android,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"

In [67]:
df.tail()

,Unnamed: 0,time,language,source,group,hashtag
1587772,556770,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,[]
1587773,556771,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,"['조승연', 'CHOSEUNGYOUN', 'X1', 'KCON2019THAILAND']"
1587774,556772,2019-09-29 17:30:55,en,Twitter for Android,17 pm,"['KCON2019THAILAND', 'KCON19TH', 'KCON_Concert..."
1587775,556773,2019-09-29 17:30:55,th,Twitter Web App,17 pm,"['남도현', 'NAMDOHYON', 'KCON19TH', 'X1_KCON', 'โ..."
1587776,556774,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,['JB']

In [68]:
df.drop('Unnamed: 0', inplace=True, axis=1)

In [69]:
df

,time,language,source,group,hashtag
0,2019-09-27 17:15:51,en,Twitter for iPhone,17 pm,['KCON2019THAILAND']
1,2019-09-27 17:15:51,th,Twitter for Android,17 pm,"['BamBam', 'GOT7', 'Got7Homecoming', 'WelcomeG..."
2,2019-09-27 17:15:51,es,Twitter for iPhone,17 pm,"['X1', 'X1FlyHighToThailand', 'KCON19TH']"
3,2019-09-27 17:15:51,en,Twitter for Android,17 pm,"['KIMWOOSEOK', 'WelcomeX1toThailand']"
4,2019-09-27 17:15:51,th,Twitter for Android,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"
5,2019-09-27 17:15:51,th,Twitter for Android,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"
6,2019-09-27 17:15:52,th,Twitter for Android,17 pm,[]
7,2019-09-27 17:15:52,th,Twitter for Android,17 pm,"['Jinyoung', 'GOT7', 'Got7Homecoming', 'Welcom..."
8,2019-09-27 17:15:52,th,Twitter for Android,17 pm,"['BamBam', 'GOT7_Homecoming', 'WelcomeGOT7toTh..."
9,2019-09-27 17:15:52,en,Twitter for Android,17 pm,"['KIMYOHAN', 'X1FlyHighToThailand', 'X1', 'X1_..."
10,2019-09-27 17:15:52,th,Twitter for iPhone,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"
11,2019-09-27 17:15:52,th,Twitter for iPhone,17 pm,[]
12,2019-09-27 17:15:53,th,Twitter for iPhone,17 pm,"['AISPLAYLive', 'KCON2019THAILAND', 'ทีมหน้าจอ']"
13,2019-09-27 17:15:53,th,Twitter for iPhone,17 pm,['KCON2019THAILAND']
14,2019-09-27 17:15:53,th,Twitter for iPhone,17 pm,[]
15,2019-09-27 17:15:53,th,Twitter for Android,17 pm,"['BamBam', 'GOT7_Homecoming', 'WelcomeGOT7toTh..."
16,2019-09-27 17:15:53,th,Twitter for iPhone,17 pm,"['X1FlyHighToThailand', 'KCON2019THAILAND']"
17,2019-09-27 17:15:54,und,Twitter for Android,17 pm,"['X1', 'X1FlyHighToThailand', 'KCON2019THAILAN..."
18,2019-09-27 17:15:54,th,Twitter for iPhone,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"
19,2019-09-27 17:15:54,und,Twitter for iPad,17 pm,[]
20,2019-09-27 17:15:54,th,Twitter for iPhone,17 pm,[]
21,2019-09-27 17:15:54,th,Twitter for iPhone,17 pm,[]
22,2019-09-27 17:15:54,th,Twitter for Android,17 pm,[]
23,2019-09-27 17:15:54,th,Twitter for Android,17 pm,['KCON2019THAILAND']
24,2019-09-27 17:15:55,th,Twitter for Android,17 pm,"['GOT7', 'GOT7_Homecoming', 'KCON2019THAILAND']"
25,2019-09-27 17:15:55,th,Twitter for iPhone,17 pm,"['BamBam', 'GOT7_Homecoming', 'WelcomeGOT7toTh..."
26,2019-09-27 17:15:55,th,Twitter for iPhone,17 pm,"['BamBam', 'GOT7_Homecoming', 'WelcomeGOT7toTh..."
27,2019-09-27 17:15:55,th,Twitter Web App,17 pm,['KCON2019THAILAND']
28,2019-09-27 17:15:55,th,Twitter for iPhone,17 pm,"['AB6IX', 'KCON2019THAILAND']"
29,2019-09-27 17:15:55,th,Twitter for Android,17 pm,"['AISPLAYLive', 'KCON2019THAILAND', 'ทีมหน้าจอ']"
...,...,...,...,...,...
1587747,2019-09-29 17:30:54,en,Twitter for iPhone,17 pm,"['GOT7', 'TwitterMirror', 'KCON2019THAILAND']"
1587748,2019-09-29 17:30:54,und,Twitter for Android,17 pm,"['KCON2019THAILAND', 'X1', 'REDCARPET', 'KCON'..."
1587749,2019-09-29 17:30:54,th,Twitter for iPhone,17 pm,[]
1587750,2019-09-29 17:30:54,th,Twitter for Android,17 pm,[]
1587751,2019-09-29 17:30:54,th,Twitter for Android,17 pm,[]
1587752,2019-09-29 17:30:54,th,Twitter for Android,17 pm,['KCONTHAILAND2019']
1587753,2019-09-29 17:30:54,th,Twitter for Android,17 pm,[]
1587754,2019-09-29 17:30:54,th,Twitter for iPad,17 pm,"['IZONE', '강혜원', 'KCON2019THAILAND']"
1587755,2019-09-29 17:30:54,th,Twitter for Android,17 pm,['StrayKids']
1587756,2019-09-29 17:30:55,und,Twitter for Android,17 pm,"['KCON2019THAILAND', 'IZONE', 'REDCARPET', 'KC..."
1587757,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,"['KCONTHAILAND2019', 'KIMJAEHWAN_KCON']"
1587758,2019-09-29 17:30:55,en,Twitter for Android,17 pm,[]
1587759,2019-09-29 17:30:55,th,Twitter for Android,17 pm,"['KCON19TH', 'KCONTHAILAND2019', 'woojin', 'AB..."
1587760,2019-09-29 17:30:55,in,Twitter for iPhone,17 pm,"['Kcon2019Thailand', 'X1', '우석', '김우석', 'WOOSE..."
1587761,2019-09-29 17:30:55,en,Twitter for iPhone,17 pm,"['KCON2019THAILAND', '조승연', 'CHOSEUNGYOUN']"
1587762,2019-09-29 17:30:55,th,Twitter for iPad,17 pm,"['KCONTHAILAND2019', 'กองทัพพีค']"
1587763,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,"['X1', 'KCON2019THAILAND']"
1587764,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,['KCONTHAILAND2019']
1587765,2019-09-29 17:30:55,th,Twitter for Android,17 pm,['KCONTHAILAND2019']
1587766,2019-09-29 17:30:55,en,Twitter for Android,17 pm,['KCONTHAILAND2019']
1587767,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,['KCONTHAILAND2019']
1587768,2019-09-29 17:30:55,ja,Twitter for iPhone,17 pm,"['X1', '이한결', 'KCON19THAILAND', 'KCON19TH']"
1587769,2019-09-29 17:30:55,th,Twitter for Android,17 pm,"['AB6IX_KCON', 'KCONTHAILAND2019']"
1587770,2019-09-29 17:30:55,th,Twitter for Android,17 pm,[]
1587771,2019-09-29 17:30:55,th,Twitter for Android,17 pm,[]
1587772,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,[]
1587773,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,"['조승연', 'CHOSEUNGYOUN', 'X1', 'KCON2019THAILAND']"
1587774,2019-09-29 17:30:55,en,Twitter for Android,17 pm,"['KCON2019THAILAND', 'KCON19TH', 'KCON_Concert..."
1587775,2019-09-29 17:30:55,th,Twitter Web App,17 pm,"['남도현', 'NAMDOHYON', 'KCON19TH', 'X1_KCON', 'โ..."
1587776,2019-09-29 17:30:55,th,Twitter for iPhone,17 pm,['JB']